import type { LegalDocs } from "./types";

export const terms: LegalDocs = {
  en: {
    title: "Terms of Use",
    intro: "These terms govern your use of ACCA USA, an online learning platform for ACCA and FIA exam preparation, operated by {operator}. By creating an account you accept them.",
    sections: [
      { heading: "1. Who we are", body: ["The service is operated by {operator}, {address}, tax ID {taxId}. Contact: {contact}.", "ACCA USA is an independent learning platform. ACCA and FIA are trademarks of their respective owners and are used for identification only; we are not affiliated with or endorsed by them."] },
      { heading: "2. Your account", body: ["You must give accurate details and keep your password confidential. You are responsible for activity under your account. Tell us at once if you suspect unauthorised use.", "We may suspend an account that breaks these terms or puts other users or the service at risk."] },
      { heading: "3. What you get", body: ["Access to the courses, materials, practice questions, tests and exams of the platforms you are enrolled in or have paid for. Free enrolment gives access only to what is published as free; paid access starts only after the payment is confirmed by our payment provider, not when you return from the payment page.", "We do not guarantee any exam result, pass rate or career outcome."] },
      { heading: "4. Materials and intellectual property", body: ["All materials belong to us or our licensors. You receive a personal, non-transferable right to view them for your own study.", "Materials are provided for viewing inside the platform. You must not copy, record, redistribute, resell, publish or share them or your access with others. Technical measures (such as access checks and watermarks that identify your account) are used to protect them; attempting to bypass them is a breach of these terms."] },
      { heading: "5. Acceptable use", body: ["Do not attempt to access other users' data, disrupt the service, scan it for vulnerabilities without our written permission, upload unlawful or harmful content, or use automated tools to collect content."] },
      { heading: "6. Prices and payment", body: ["Prices are shown before you pay. Card details are entered on the payment provider's page and never reach our servers. Refunds are described in the Refund Policy.", "If a payment is refunded in full, the access it granted is withdrawn."] },
      { heading: "7. Your content", body: ["Notes and other content you create stay yours and are private to your account. You allow us to store and process them to provide the service."] },
      { heading: "8. Availability and changes", body: ["We work to keep the service available but do not promise uninterrupted operation. We may change or discontinue features, and update these terms. When the text changes materially you will be asked to accept the new version at your next sign-in; if you do not accept, you cannot continue to use the service."] },
      { heading: "9. Liability", body: ["To the extent permitted by law, we are not liable for indirect or consequential loss, and our total liability for a claim is limited to the amount you paid in the 12 months before it. Nothing here limits liability that cannot be limited by law, including your statutory consumer rights."] },
      { heading: "10. Governing law", body: ["These terms are governed by the law of {law}. Mandatory consumer-protection rules of your country of residence remain unaffected."] },
    ],
  },
  ru: {
    title: "Условия использования",
    intro: "Настоящие условия регулируют использование платформы ACCA USA — онлайн-обучения для подготовки к экзаменам ACCA и FIA, оператором которой является {operator}. Создавая аккаунт, вы принимаете эти условия.",
    sections: [
      { heading: "1. Кто мы", body: ["Сервис предоставляет {operator}, {address}, ИНН/STIR {taxId}. Контакт: {contact}.", "ACCA USA — независимая образовательная платформа. ACCA и FIA — товарные знаки их владельцев, используются только для обозначения; мы не связаны с ними и не одобрены ими."] },
      { heading: "2. Ваш аккаунт", body: ["Вы обязаны указывать достоверные данные и хранить пароль в тайне. Вы отвечаете за действия в своём аккаунте. Сообщите нам сразу, если подозреваете несанкционированный доступ.", "Мы можем приостановить аккаунт, нарушающий эти условия или создающий риск для других пользователей и сервиса."] },
      { heading: "3. Что вы получаете", body: ["Доступ к курсам, материалам, практическим вопросам, тестам и экзаменам платформ, на которые вы записаны или которые оплатили. Бесплатная запись открывает только то, что опубликовано как бесплатное; платный доступ начинается только после подтверждения платежа нашим платёжным провайдером, а не после возврата со страницы оплаты.", "Мы не гарантируем результат экзамена, процент сдачи или карьерный результат."] },
      { heading: "4. Материалы и интеллектуальная собственность", body: ["Все материалы принадлежат нам или нашим лицензиарам. Вы получаете личное, непередаваемое право просматривать их для собственного обучения.", "Материалы предоставляются для просмотра внутри платформы. Запрещено копировать, записывать, распространять, перепродавать, публиковать материалы или передавать доступ другим лицам. Для защиты используются технические меры (проверки доступа, водяные знаки с данными вашего аккаунта); попытка их обойти является нарушением условий."] },
      { heading: "5. Допустимое использование", body: ["Не пытайтесь получить доступ к данным других пользователей, нарушать работу сервиса, сканировать его на уязвимости без нашего письменного разрешения, загружать незаконный или вредоносный контент, использовать автоматические средства для сбора контента."] },
      { heading: "6. Цены и оплата", body: ["Цены показываются до оплаты. Данные карты вводятся на странице платёжного провайдера и не попадают на наши серверы. Возврат средств описан в Политике возврата.", "При полном возврате платежа доступ, который он открыл, закрывается."] },
      { heading: "7. Ваш контент", body: ["Заметки и другой созданный вами контент остаются вашими и видны только вашему аккаунту. Вы разрешаете нам хранить и обрабатывать их для работы сервиса."] },
      { heading: "8. Доступность и изменения", body: ["Мы стремимся к бесперебойной работе, но не обещаем её. Мы можем изменять и прекращать функции, а также обновлять эти условия. При существенном изменении текста при следующем входе вам будет предложено принять новую редакцию; без принятия продолжить пользоваться сервисом нельзя."] },
      { heading: "9. Ответственность", body: ["В пределах, допускаемых законом, мы не отвечаем за косвенные убытки и упущенную выгоду, а наша общая ответственность по претензии ограничена суммой, уплаченной вами за последние 12 месяцев. Ничто здесь не ограничивает ответственность, которую нельзя ограничить по закону, включая ваши права потребителя."] },
      { heading: "10. Применимое право", body: ["К условиям применяется право: {law}. Императивные нормы о защите прав потребителей страны вашего проживания не затрагиваются."] },
    ],
  },
  uz: {
    title: "Foydalanish shartlari",
    intro: "Ushbu shartlar {operator} tomonidan boshqariladigan, ACCA va FIA imtihonlariga tayyorgarlik uchun onlayn o‘quv platformasi ACCA USA’dan foydalanishni tartibga soladi. Hisob yaratish orqali siz ularni qabul qilasiz.",
    sections: [
      { heading: "1. Biz kimmiz", body: ["Xizmatni {operator}, {address}, STIR {taxId} taqdim etadi. Aloqa: {contact}.", "ACCA USA — mustaqil o‘quv platformasi. ACCA va FIA o‘z egalarining tovar belgilaridir va faqat identifikatsiya uchun ishlatiladi; biz ular bilan bog‘liq emasmiz va ular tomonidan tasdiqlanmaganmiz."] },
      { heading: "2. Hisobingiz", body: ["To‘g‘ri ma’lumot kiritishingiz va parolni sir saqlashingiz shart. Hisobingizdagi harakatlar uchun o‘zingiz javobgarsiz. Ruxsatsiz kirishdan shubhalansangiz, darhol xabar bering.", "Ushbu shartlarni buzgan yoki boshqa foydalanuvchilar va xizmatga xavf tug‘diradigan hisobni to‘xtatib qo‘yishimiz mumkin."] },
      { heading: "3. Siz nima olasiz", body: ["Yozilgan yoki to‘lov qilgan platformalaringizdagi kurslar, materiallar, mashq savollari, testlar va imtihonlarga kirish. Bepul yozilish faqat bepul deb e’lon qilingan qismga kirish beradi; pulli kirish to‘lov sahifasidan qaytganingizda emas, balki to‘lov provayderimiz to‘lovni tasdiqlagandan keyingina boshlanadi.", "Imtihon natijasi, topshirish ko‘rsatkichi yoki martaba natijasiga kafolat bermaymiz."] },
      { heading: "4. Materiallar va intellektual mulk", body: ["Barcha materiallar bizga yoki litsenziarlarimizga tegishli. Siz ularni shaxsiy o‘qish uchun ko‘rish bo‘yicha shaxsiy, o‘tkazilmaydigan huquq olasiz.", "Materiallar platforma ichida ko‘rish uchun beriladi. Ularni nusxalash, yozib olish, tarqatish, qayta sotish, e’lon qilish yoki kirishni boshqalarga berish taqiqlanadi. Himoya uchun texnik choralar (kirish tekshiruvlari, hisobingizni ko‘rsatuvchi suv belgilari) qo‘llaniladi; ularni chetlab o‘tishga urinish shartlarni buzishdir."] },
      { heading: "5. Ruxsat etilgan foydalanish", body: ["Boshqa foydalanuvchilar ma’lumotlariga kirishga, xizmat ishini buzishga, yozma ruxsatimizsiz zaifliklarni skanerlashga, noqonuniy yoki zararli kontent yuklashga, kontentni yig‘ish uchun avtomatik vositalardan foydalanishga urinmang."] },
      { heading: "6. Narxlar va to‘lov", body: ["Narxlar to‘lovdan oldin ko‘rsatiladi. Karta ma’lumotlari to‘lov provayderi sahifasida kiritiladi va serverlarimizga tushmaydi. Pulni qaytarish Qaytarish siyosatida bayon etilgan.", "To‘lov to‘liq qaytarilsa, u bergan kirish bekor qilinadi."] },
      { heading: "7. Sizning kontentingiz", body: ["Qaydlar va siz yaratgan boshqa kontent sizniki bo‘lib qoladi va faqat hisobingizga ko‘rinadi. Xizmatni ko‘rsatish uchun ularni saqlash va qayta ishlashga ruxsat berasiz."] },
      { heading: "8. Mavjudlik va o‘zgarishlar", body: ["Xizmat uzluksiz ishlashiga intilamiz, ammo va’da bermaymiz. Imkoniyatlarni o‘zgartirishimiz yoki to‘xtatishimiz, shuningdek shartlarni yangilashimiz mumkin. Matn sezilarli o‘zgarganda keyingi kirishda yangi tahrirni qabul qilish so‘raladi; qabul qilmasangiz, xizmatdan foydalanishni davom ettira olmaysiz."] },
      { heading: "9. Javobgarlik", body: ["Qonun ruxsat bergan darajada biz bilvosita zararlar uchun javobgar emasmiz, da’vo bo‘yicha umumiy javobgarligimiz oxirgi 12 oyda to‘lagan summangiz bilan cheklanadi. Bu yerdagi hech narsa qonun bo‘yicha cheklab bo‘lmaydigan javobgarlikni, shu jumladan iste’molchi huquqlaringizni cheklamaydi."] },
      { heading: "10. Qo‘llaniladigan huquq", body: ["Ushbu shartlarga {law} huquqi qo‘llaniladi. Yashash mamlakatingizdagi iste’molchi huquqlarini himoya qilish bo‘yicha majburiy normalar o‘z kuchida qoladi."] },
    ],
  },
};
