import "server-only";
import { randomUUID } from "node:crypto";
import { createReadStream, createWriteStream, existsSync, mkdirSync, readFileSync, readdirSync, statSync, unlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { Readable } from "node:stream";
import { pipeline } from "node:stream/promises";
import type { OpenedFile, StorageProvider, StoredFileMeta } from "./contracts";
import { sanitizeFileName } from "./validation";
import { seedAudioBase64, seedImageBase64, seedVideoBase64 } from "./seed-assets";

/**
 * Demo storage: files live in the OS temp directory. No external service, no credentials.
 * Ids are random UUIDs (never user-supplied paths) so path traversal is impossible.
 * Everything here is disposable demo data.
 */
const ROOT = join(tmpdir(), "acca-usa-demo", "uploads");
const ID_RE = /^[a-zA-Z0-9-]{8,64}$/;
const GC_AFTER_MS = 60 * 60 * 1000;

const bin = (id: string) => join(ROOT, `${id}.bin`);
const metaPath = (id: string) => join(ROOT, `${id}.json`);

function ensureRoot() {
  mkdirSync(ROOT, { recursive: true, mode: 0o700 });
}

function buildSamplePdf(): Buffer {
  const objs = [
    "<< /Type /Catalog /Pages 2 0 R >>",
    "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
    "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>",
    "",
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
  ];
  const text = ["BT /F1 22 Tf 60 760 Td (ACCA USA - sample workbook) Tj ET", "BT /F1 12 Tf 60 720 Td (Cost classification: fixed, variable, step and semi-variable costs.) Tj ET", "BT /F1 12 Tf 60 700 Td (Demo file generated by the demo storage provider.) Tj ET"].join("\n");
  objs[3] = `<< /Length ${text.length} >>\nstream\n${text}\nendstream`;
  let out = "%PDF-1.4\n";
  const offsets: number[] = [];
  objs.forEach((o, i) => {
    offsets.push(out.length);
    out += `${i + 1} 0 obj\n${o}\nendobj\n`;
  });
  const xref = out.length;
  out += `xref\n0 ${objs.length + 1}\n0000000000 65535 f \n${offsets.map((o) => `${String(o).padStart(10, "0")} 00000 n \n`).join("")}trailer\n<< /Size ${objs.length + 1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF\n`;
  return Buffer.from(out, "latin1");
}

const GLOSSARY = [
  "ACCA USA - glossary (demo file)",
  "",
  "Stakeholder: any person or group affected by, or able to affect, the organisation.",
  "Shareholder: an owner of the company through shares.",
  "Governance: the system by which organisations are directed and controlled.",
  "",
].join("\n");

/** Demo files shipped with the demo provider: ids are fixed so seed materials can reference them. */
const seeds: { id: string; name: string; mime: string; data: () => Buffer }[] = [
  { id: "seed-ma-workbook", name: "cost-classification-workbook.pdf", mime: "application/pdf", data: buildSamplePdf },
  { id: "seed-bt-lecture", name: "stakeholders-lecture.mp4", mime: "video/mp4", data: () => Buffer.from(seedVideoBase64, "base64") },
  { id: "seed-bt-overview", name: "stakeholders-overview.pdf", mime: "application/pdf", data: buildSamplePdf },
  { id: "seed-bt-audio", name: "stakeholders-podcast.mp3", mime: "audio/mpeg", data: () => Buffer.from(seedAudioBase64, "base64") },
  { id: "seed-bt-diagram", name: "stakeholders-diagram.png", mime: "image/png", data: () => Buffer.from(seedImageBase64, "base64") },
  { id: "seed-bt-glossary", name: "glossary.txt", mime: "text/plain; charset=utf-8", data: () => Buffer.from(GLOSSARY, "utf8") },
];

function ensureSeed() {
  for (const seed of seeds) {
    if (existsSync(metaPath(seed.id))) continue;
    ensureRoot();
    const data = seed.data();
    writeFileSync(bin(seed.id), data);
    const meta: StoredFileMeta = { id: seed.id, name: seed.name, mime: seed.mime, size: data.length, createdAt: new Date().toISOString(), ownerId: "system", attached: true };
    writeFileSync(metaPath(seed.id), JSON.stringify(meta));
  }
}

function readMeta(id: string): StoredFileMeta | null {
  if (!ID_RE.test(id)) return null;
  try {
    return JSON.parse(readFileSync(metaPath(id), "utf8")) as StoredFileMeta;
  } catch {
    return null;
  }
}

function gc() {
  try {
    const now = Date.now();
    for (const f of readdirSync(ROOT)) {
      if (!f.endsWith(".json")) continue;
      const m = readMeta(f.slice(0, -5));
      if (m && !m.attached && now - new Date(m.createdAt).getTime() > GC_AFTER_MS) removeFiles(m.id);
    }
  } catch {
    /* best effort */
  }
}

function removeFiles(id: string) {
  for (const p of [bin(id), metaPath(id)]) {
    try {
      unlinkSync(p);
    } catch {
      /* already gone */
    }
  }
}

export class DemoStorageProvider implements StorageProvider {
  readonly name = "demo" as const;

  async put({ ownerId, file, mime, durationSeconds }: { ownerId: string; file: File; mime: string; durationSeconds?: number }): Promise<StoredFileMeta> {
    ensureRoot();
    ensureSeed();
    gc();
    const id = randomUUID();
    await pipeline(Readable.fromWeb(file.stream() as never), createWriteStream(bin(id), { mode: 0o600 }));
    const meta: StoredFileMeta = { id, name: sanitizeFileName(file.name), mime, size: file.size, createdAt: new Date().toISOString(), ownerId, attached: false, durationSeconds };
    writeFileSync(metaPath(id), JSON.stringify(meta), { mode: 0o600 });
    return meta;
  }

  async stat(id: string): Promise<StoredFileMeta | null> {
    ensureSeed();
    return readMeta(id);
  }

  async open(id: string, range?: { start: number; end?: number }): Promise<OpenedFile | null> {
    ensureSeed();
    const meta = readMeta(id);
    if (!meta || !existsSync(bin(id))) return null;
    const size = statSync(bin(id)).size;
    const start = Math.min(Math.max(range?.start ?? 0, 0), Math.max(size - 1, 0));
    const end = Math.min(range?.end ?? size - 1, size - 1);
    const stream = Readable.toWeb(createReadStream(bin(id), { start, end })) as unknown as ReadableStream<Uint8Array>;
    return { file: meta, stream, start, end };
  }

  async delete(id: string): Promise<void> {
    if (ID_RE.test(id) && !id.startsWith("seed-")) removeFiles(id);
  }

  async replace(id: string, input: { ownerId: string; file: File; mime: string; durationSeconds?: number }): Promise<StoredFileMeta> {
    const next = await this.put(input);
    await this.delete(id);
    return next;
  }

  async markAttached(id: string, attached: boolean): Promise<void> {
    const meta = readMeta(id);
    if (!meta) return;
    writeFileSync(metaPath(id), JSON.stringify({ ...meta, attached }), { mode: 0o600 });
  }

  async exists(id: string): Promise<boolean> {
    ensureSeed();
    return readMeta(id) !== null && existsSync(bin(id));
  }

  /** The demo provider has no signing key and no public origin: files are only served through /api/files/[id]. */
  async signedUrl(): Promise<string | null> {
    return null;
  }
}
